stages:
  - testing # Запуск тестов

variables:  # Переменные
  TEST_NAME:
    value: ""
    description: "Название теста"
  PROCESS:
    value: "1"
    description: "Количество потоков"

Run_Job: # Название job
  stage: testing # Первый stage, который нужно выполнить
  image: python:3.8-alpine # Образ выполнения
  before_script:
    - pip install -r requirements.txt  # предварительный скрипт
    - black ./tests
  script:
    - pytest -n=$PROCESS -v -s -k "test_${TEST_NAME}" --alluredir=./allure-results
  allow_failure: true # Это позволит нам продолжить выполнение пайплайна в случае, если тесты упали.
  artifacts: # Сущность, с помощью которой, мы сохраним результат тестирования.
      when: always # Сохранять всегда
      paths:
        - ./allure-results # Здесь будет сохранен отчет
      expire_in: 1 day # Да, он будет удален через день. Нет смысла хранить его в течение длительного срока.
